// Mock data for preview mode when database is unavailable
import type { Restaurant, Category, MenuItem, ItemVariant, Topping, DeliveryZone, Allergen, Additive } from "./types"

export const MOCK_RESTAURANT: Restaurant = {
  id: 1,
  name: "Bella Marina",
  slug: "bella-marina",
  domain: null,
  logo_url: null,
  hero_image_url: "/italian-restaurant-interior.png",
  primary_color: "#e63946",
  slogan: "Authentische italienische Küche",
  banner_text: "Willkommen bei Bella Marina!",
  address: "Musterstraße 123, 12345 Musterstadt",
  email: "info@bella-marina.de",
  phone: "+49 123 456789",
  owner_name: "Marco Rossi",
  impressum: "Bella Marina GmbH\nMusterstraße 123\n12345 Musterstadt",
  opening_hours: {
    mon: { open: "11:00", close: "22:00" },
    tue: { open: "11:00", close: "22:00" },
    wed: { open: "11:00", close: "22:00" },
    thu: { open: "11:00", close: "22:00" },
    fri: { open: "11:00", close: "23:00" },
    sat: { open: "12:00", close: "23:00" },
    sun: { open: "12:00", close: "21:00" },
  },
  fee_type: "percentage",
  fee_value: 5,
  admin_password_hash: null,
  info_text: "Frische Zutaten, traditionelle Rezepte",
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  seo_title: "Bella Marina - Italienisches Restaurant",
  seo_description: "Authentische italienische Küche mit frischen Zutaten",
  google_business_url: null,
  facebook_url: null,
  instagram_url: null,
  city: "Musterstadt",
  postal_code: "12345",
  country: "DE",
  latitude: null,
  longitude: null,
  cuisine_type: "Italienisch",
  price_range: "$$",
  accepts_reservations: true,
  payment_methods: ["cash", "card"],
  custom_domain: null,
  legal_name: "Bella Marina GmbH",
  legal_address: "Musterstraße 123, 12345 Musterstadt",
  legal_contact: "info@bella-marina.de",
  tax_id: "DE123456789",
  privacy_policy_content: null,
  legal_disclaimer: null,
  allow_super_admin_revenue_view: true,
  super_admin_restaurant_password: null,
  encrypted_admin_password: null,
  admin_password_set: false,
  ai_assistant_enabled: false,
}

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, restaurant_id: 1, name: "Pizza", sort_order: 1, created_at: new Date().toISOString() },
  { id: 2, restaurant_id: 1, name: "Pasta", sort_order: 2, created_at: new Date().toISOString() },
  { id: 3, restaurant_id: 1, name: "Salate", sort_order: 3, created_at: new Date().toISOString() },
  { id: 4, restaurant_id: 1, name: "Getränke", sort_order: 4, created_at: new Date().toISOString() },
]

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    restaurant_id: 1,
    category_id: 1,
    name: "Pizza Margherita",
    description: "Tomatensoße, Mozzarella, frisches Basilikum",
    image_url: "/pizza-margherita.png",
    base_price: 9.5,
    toppings_allowed: true,
    is_upsell: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    calories: 850,
    allergens: ["gluten", "milk"],
    dietary_info: ["vegetarian"],
  },
  {
    id: 2,
    restaurant_id: 1,
    category_id: 1,
    name: "Pizza Salami",
    description: "Tomatensoße, Mozzarella, würzige Salami",
    image_url: "/pizza-salami.png",
    base_price: 10.5,
    toppings_allowed: true,
    is_upsell: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    calories: 950,
    allergens: ["gluten", "milk"],
    dietary_info: [],
  },
  {
    id: 3,
    restaurant_id: 1,
    category_id: 2,
    name: "Spaghetti Bolognese",
    description: "Hausgemachte Fleischsoße nach Familienrezept",
    image_url: "/spaghetti-bolognese.png",
    base_price: 11.0,
    toppings_allowed: false,
    is_upsell: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    calories: 780,
    allergens: ["gluten", "egg"],
    dietary_info: [],
  },
  {
    id: 4,
    restaurant_id: 1,
    category_id: 2,
    name: "Penne Arrabiata",
    description: "Scharfe Tomatensoße mit Knoblauch und Chili",
    image_url: "/penne-arrabiata.jpg",
    base_price: 9.5,
    toppings_allowed: false,
    is_upsell: false,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    calories: 650,
    allergens: ["gluten"],
    dietary_info: ["vegan"],
  },
  {
    id: 5,
    restaurant_id: 1,
    category_id: 3,
    name: "Insalata Mista",
    description: "Gemischter Salat mit Hausdressing",
    image_url: "/mixed-salad.png",
    base_price: 7.5,
    toppings_allowed: false,
    is_upsell: false,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    calories: 250,
    allergens: [],
    dietary_info: ["vegan", "gluten-free"],
  },
  {
    id: 6,
    restaurant_id: 1,
    category_id: 4,
    name: "Cola 0,5L",
    description: null,
    image_url: "/generic-soda-bottle.png",
    base_price: 3.0,
    toppings_allowed: false,
    is_upsell: true,
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    calories: 210,
    allergens: [],
    dietary_info: ["vegan"],
  },
]

export const MOCK_VARIANTS: ItemVariant[] = [
  { id: 1, menu_item_id: 1, name: "Klein (26cm)", price_modifier: 0, sort_order: 1 },
  { id: 2, menu_item_id: 1, name: "Mittel (30cm)", price_modifier: 2, sort_order: 2 },
  { id: 3, menu_item_id: 1, name: "Groß (32cm)", price_modifier: 4, sort_order: 3 },
  { id: 4, menu_item_id: 2, name: "Klein (26cm)", price_modifier: 0, sort_order: 1 },
  { id: 5, menu_item_id: 2, name: "Mittel (30cm)", price_modifier: 2, sort_order: 2 },
  { id: 6, menu_item_id: 2, name: "Groß (32cm)", price_modifier: 4, sort_order: 3 },
]

export const MOCK_TOPPINGS: Topping[] = [
  { id: 1, restaurant_id: 1, name: "Extra Käse", price: 1.5, is_available: true },
  { id: 2, restaurant_id: 1, name: "Schinken", price: 1.5, is_available: true },
  { id: 3, restaurant_id: 1, name: "Champignons", price: 1.0, is_available: true },
  { id: 4, restaurant_id: 1, name: "Oliven", price: 1.0, is_available: true },
  { id: 5, restaurant_id: 1, name: "Paprika", price: 1.0, is_available: true },
]

export const MOCK_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 1,
    restaurant_id: 1,
    name: "Zone 1 (0-3km)",
    price: 2.0,
    postal_codes: ["12345"],
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    restaurant_id: 1,
    name: "Zone 2 (3-5km)",
    price: 3.5,
    postal_codes: ["12346", "12347"],
    created_at: new Date().toISOString(),
  },
]

export const MOCK_REVIEW_STATS = { avgRating: 4.5, reviewCount: 127 }

export const MOCK_REVIEWS = [
  {
    id: 1,
    restaurant_id: 1,
    customer_name: "Maria S.",
    customer_email: null,
    rating: 5,
    title: "Beste Pizza in der Stadt!",
    comment: "Die Pizza war fantastisch, genau wie in Italien. Schnelle Lieferung!",
    is_approved: true,
    is_verified_purchase: true,
    order_id: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 2,
    restaurant_id: 1,
    customer_name: "Thomas K.",
    customer_email: null,
    rating: 4,
    title: "Sehr lecker",
    comment: "Tolle Pasta, wird definitiv wieder bestellt.",
    is_approved: true,
    is_verified_purchase: true,
    order_id: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
]

export const MOCK_ALLERGENS: Allergen[] = [
  { id: 1, restaurant_id: 1, code: "A", name: "Glutenhaltiges Getreide", type: "allergen" },
  { id: 2, restaurant_id: 1, code: "B", name: "Krebstiere", type: "allergen" },
  { id: 3, restaurant_id: 1, code: "C", name: "Eier", type: "allergen" },
  { id: 4, restaurant_id: 1, code: "D", name: "Fisch", type: "allergen" },
  { id: 5, restaurant_id: 1, code: "E", name: "Erdnüsse", type: "allergen" },
  { id: 6, restaurant_id: 1, code: "F", name: "Soja", type: "allergen" },
  { id: 7, restaurant_id: 1, code: "G", name: "Milch/Laktose", type: "allergen" },
  { id: 8, restaurant_id: 1, code: "H", name: "Schalenfrüchte", type: "allergen" },
  { id: 9, restaurant_id: 1, code: "I", name: "Sellerie", type: "allergen" },
  { id: 10, restaurant_id: 1, code: "J", name: "Senf", type: "allergen" },
  { id: 11, restaurant_id: 1, code: "K", name: "Sesam", type: "allergen" },
  { id: 12, restaurant_id: 1, code: "L", name: "Schwefeldioxid/Sulfite", type: "allergen" },
  { id: 13, restaurant_id: 1, code: "M", name: "Lupinen", type: "allergen" },
  { id: 14, restaurant_id: 1, code: "N", name: "Weichtiere", type: "allergen" },
]

export const MOCK_ADDITIVES: Additive[] = [
  { id: 15, restaurant_id: 1, code: "1", name: "mit Farbstoff", type: "additive" },
  { id: 16, restaurant_id: 1, code: "2", name: "mit Konservierungsstoff", type: "additive" },
  { id: 17, restaurant_id: 1, code: "3", name: "mit Antioxidationsmittel", type: "additive" },
  { id: 18, restaurant_id: 1, code: "4", name: "mit Geschmacksverstärker", type: "additive" },
  { id: 19, restaurant_id: 1, code: "5", name: "geschwefelt", type: "additive" },
  { id: 20, restaurant_id: 1, code: "6", name: "geschwärzt", type: "additive" },
  { id: 21, restaurant_id: 1, code: "7", name: "gewachst", type: "additive" },
  { id: 22, restaurant_id: 1, code: "8", name: "mit Phosphat", type: "additive" },
  { id: 23, restaurant_id: 1, code: "9", name: "mit Süßungsmittel", type: "additive" },
  { id: 24, restaurant_id: 1, code: "10", name: "enthält eine Phenylalaninquelle", type: "additive" },
  { id: 25, restaurant_id: 1, code: "11", name: "koffeinhaltig", type: "additive" },
  { id: 26, restaurant_id: 1, code: "12", name: "chininhaltig", type: "additive" },
]
