-- Fix column names in restaurant retrieval functions
-- The functions were using old column names (street, zip) instead of (address, postal_code)

-- Drop and recreate get_restaurant_by_slug with correct columns
DROP FUNCTION IF EXISTS get_restaurant_by_slug(TEXT);

CREATE OR REPLACE FUNCTION get_restaurant_by_slug(p_slug TEXT)
RETURNS TABLE (
  id INT,
  name TEXT,
  slug TEXT,
  domain TEXT,
  slogan TEXT,
  banner_text TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  postal_code TEXT,
  country TEXT,
  logo_url TEXT,
  hero_image_url TEXT,
  primary_color TEXT,
  text_color TEXT,
  background_color TEXT,
  opening_hours JSONB,
  accepts_preorders BOOLEAN,
  manually_closed BOOLEAN,
  is_active BOOLEAN,
  owner_name TEXT,
  impressum TEXT,
  checkout_info_text TEXT,
  admin_password_hash TEXT,
  stripe_account_id TEXT,
  stripe_onboarding_complete BOOLEAN,
  stripe_charges_enabled BOOLEAN,
  stripe_payouts_enabled BOOLEAN,
  is_stripe_live_mode BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  accepts_cash BOOLEAN,
  accepts_card BOOLEAN,
  show_revenue_in_dashboard BOOLEAN,
  notification_enabled BOOLEAN,
  ai_assistant_enabled BOOLEAN,
  seo_title TEXT,
  seo_description TEXT,
  seo_footer_content TEXT,
  seo_keywords TEXT,
  custom_domain TEXT,
  primary_button_color TEXT,
  header_background_color TEXT,
  header_text_color TEXT,
  footer_background_color TEXT,
  footer_text_color TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    r.id,
    r.name,
    r.slug,
    r.domain,
    r.slogan,
    r.banner_text,
    r.phone,
    r.email,
    r.address,
    r.city,
    r.postal_code,
    r.country,
    r.logo_url,
    r.hero_image_url,
    r.primary_color,
    r.text_color,
    r.background_color,
    r.opening_hours,
    r.accepts_preorders,
    r.manually_closed,
    r.is_active,
    r.owner_name,
    r.impressum,
    r.checkout_info_text,
    r.admin_password_hash,
    r.stripe_account_id,
    r.stripe_onboarding_complete,
    r.stripe_charges_enabled,
    r.stripe_payouts_enabled,
    r.is_stripe_live_mode,
    r.created_at,
    r.updated_at,
    r.accepts_cash,
    r.accepts_card,
    r.show_revenue_in_dashboard,
    r.notification_enabled,
    r.ai_assistant_enabled,
    r.seo_title,
    r.seo_description,
    r.seo_footer_content,
    r.seo_keywords,
    r.custom_domain,
    r.primary_button_color,
    r.header_background_color,
    r.header_text_color,
    r.footer_background_color,
    r.footer_text_color
  FROM restaurants r
  WHERE LOWER(TRIM(r.slug)) = LOWER(TRIM(p_slug))
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- Drop and recreate get_restaurant_by_id with correct columns
DROP FUNCTION IF EXISTS get_restaurant_by_id(INT);

CREATE OR REPLACE FUNCTION get_restaurant_by_id(p_id INT)
RETURNS TABLE (
  id INT,
  name TEXT,
  slug TEXT,
  domain TEXT,
  slogan TEXT,
  banner_text TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  postal_code TEXT,
  country TEXT,
  logo_url TEXT,
  hero_image_url TEXT,
  primary_color TEXT,
  text_color TEXT,
  background_color TEXT,
  opening_hours JSONB,
  accepts_preorders BOOLEAN,
  manually_closed BOOLEAN,
  is_active BOOLEAN,
  owner_name TEXT,
  impressum TEXT,
  checkout_info_text TEXT,
  admin_password_hash TEXT,
  stripe_account_id TEXT,
  stripe_onboarding_complete BOOLEAN,
  stripe_charges_enabled BOOLEAN,
  stripe_payouts_enabled BOOLEAN,
  is_stripe_live_mode BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  accepts_cash BOOLEAN,
  accepts_card BOOLEAN,
  show_revenue_in_dashboard BOOLEAN,
  notification_enabled BOOLEAN,
  ai_assistant_enabled BOOLEAN,
  seo_title TEXT,
  seo_description TEXT,
  seo_footer_content TEXT,
  seo_keywords TEXT,
  custom_domain TEXT,
  primary_button_color TEXT,
  header_background_color TEXT,
  header_text_color TEXT,
  footer_background_color TEXT,
  footer_text_color TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    r.id,
    r.name,
    r.slug,
    r.domain,
    r.slogan,
    r.banner_text,
    r.phone,
    r.email,
    r.address,
    r.city,
    r.postal_code,
    r.country,
    r.logo_url,
    r.hero_image_url,
    r.primary_color,
    r.text_color,
    r.background_color,
    r.opening_hours,
    r.accepts_preorders,
    r.manually_closed,
    r.is_active,
    r.owner_name,
    r.impressum,
    r.checkout_info_text,
    r.admin_password_hash,
    r.stripe_account_id,
    r.stripe_onboarding_complete,
    r.stripe_charges_enabled,
    r.stripe_payouts_enabled,
    r.is_stripe_live_mode,
    r.created_at,
    r.updated_at,
    r.accepts_cash,
    r.accepts_card,
    r.show_revenue_in_dashboard,
    r.notification_enabled,
    r.ai_assistant_enabled,
    r.seo_title,
    r.seo_description,
    r.seo_footer_content,
    r.seo_keywords,
    r.custom_domain,
    r.primary_button_color,
    r.header_background_color,
    r.header_text_color,
    r.footer_background_color,
    r.footer_text_color
  FROM restaurants r
  WHERE r.id = p_id
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- Drop and recreate get_restaurant_by_domain with correct columns
DROP FUNCTION IF EXISTS get_restaurant_by_domain(TEXT);

CREATE OR REPLACE FUNCTION get_restaurant_by_domain(p_domain TEXT)
RETURNS TABLE (
  id INT,
  name TEXT,
  slug TEXT,
  domain TEXT,
  slogan TEXT,
  banner_text TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  postal_code TEXT,
  country TEXT,
  logo_url TEXT,
  hero_image_url TEXT,
  primary_color TEXT,
  text_color TEXT,
  background_color TEXT,
  opening_hours JSONB,
  accepts_preorders BOOLEAN,
  manually_closed BOOLEAN,
  is_active BOOLEAN,
  owner_name TEXT,
  impressum TEXT,
  checkout_info_text TEXT,
  admin_password_hash TEXT,
  stripe_account_id TEXT,
  stripe_onboarding_complete BOOLEAN,
  stripe_charges_enabled BOOLEAN,
  stripe_payouts_enabled BOOLEAN,
  is_stripe_live_mode BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  accepts_cash BOOLEAN,
  accepts_card BOOLEAN,
  show_revenue_in_dashboard BOOLEAN,
  notification_enabled BOOLEAN,
  ai_assistant_enabled BOOLEAN,
  seo_title TEXT,
  seo_description TEXT,
  seo_footer_content TEXT,
  seo_keywords TEXT,
  custom_domain TEXT,
  primary_button_color TEXT,
  header_background_color TEXT,
  header_text_color TEXT,
  footer_background_color TEXT,
  footer_text_color TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    r.id,
    r.name,
    r.slug,
    r.domain,
    r.slogan,
    r.banner_text,
    r.phone,
    r.email,
    r.address,
    r.city,
    r.postal_code,
    r.country,
    r.logo_url,
    r.hero_image_url,
    r.primary_color,
    r.text_color,
    r.background_color,
    r.opening_hours,
    r.accepts_preorders,
    r.manually_closed,
    r.is_active,
    r.owner_name,
    r.impressum,
    r.checkout_info_text,
    r.admin_password_hash,
    r.stripe_account_id,
    r.stripe_onboarding_complete,
    r.stripe_charges_enabled,
    r.stripe_payouts_enabled,
    r.is_stripe_live_mode,
    r.created_at,
    r.updated_at,
    r.accepts_cash,
    r.accepts_card,
    r.show_revenue_in_dashboard,
    r.notification_enabled,
    r.ai_assistant_enabled,
    r.seo_title,
    r.seo_description,
    r.seo_footer_content,
    r.seo_keywords,
    r.custom_domain,
    r.primary_button_color,
    r.header_background_color,
    r.header_text_color,
    r.footer_background_color,
    r.footer_text_color
  FROM restaurants r
  WHERE LOWER(TRIM(r.custom_domain)) = LOWER(TRIM(p_domain))
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;
